name: flutter_launchpad
description: "Flutter Library to control Novation Launchpad MIDI devices"
version: 1.0.0+3

repository: https://github.com/AlabasterAxe/fluttpad

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_midi_command: ^0.4.15
  google_fonts: ^6.2.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/novation.png
    - assets/google_fonts/